# Generated by Django 5.2.6 on 2025-09-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
    ]
