# Generated by Django 5.2.6 on 2025-09-13 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_align_with_supabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.CASCADE, to='professors.professor'),
        ),
        migrations.AlterModelTable(
            name='professor',
            table='professors',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='reviews',
        ),
    ]
