# Generated by Django 5.2.6 on 2025-09-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professor_id_alter_professor_name_and_more'),
    ]

    operations = [
    ]
